baseURL = 'https://korikov.cc/'
languageCode = 'en-us'
title = 'Archive'
theme = 'book-toc-ck'
disableKinds = ["taxonomy", "term"]

[params]
  author = "Constantine Korikov"
  header_label = "Archive"
